### ISSUE TITLE
`yarn` fails with 404

### ISSUE THREAD

**Issue by ribose-jeffreylau** [glossarist/paneron-extension-glossarist#5]
## Expected outcome

Running `yarn` should successfully install dependencies.

## Actual outcome

<details>

<summary>Click to expand</summary>

```console
> yarn
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @blueprintjs/core@3.44.2" has unmet peer dependency "react-dom@^15.3.0 || 16 || 17".
warning "@blueprintjs/core > react-transition-group@2.9.0" has unmet peer dependency "react-dom@>=15.0.0".
warning " > @blueprintjs/datetime@3.23.2" has unmet peer dependency "react-dom@^15.3.0 || 16 || 17".
warning " > @blueprintjs/select@3.16.2" has unmet peer dependency "react-dom@^15.3.0 || 16 || 17".
warning " > @riboseinc/paneron-extension-kit@2.0.0-dev31" has incorrect peer dependency "electron@^10.1.3".
warning " > @riboseinc/paneron-registry-kit@2.0.0-dev26" has incorrect peer dependency "electron@^10.1.3".
[4/4] 🔨  Building fresh packages...
[1/3] ⠈ fsevents
[3/3] ⠈ electron
error /Users/username/share/src/extension-geodetic-registry/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/username/share/src/extension-geodetic-registry/node_modules/electron
Output:
HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v10.1.2/electron-v10.1.2-darwin-arm64.zip
    at EventEmitter.<anonymous> (/Users/username/share/src/extension-geodetic-registry/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:520:28)
    at module.exports (/Users/username/share/src/extension-geodetic-registry/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/username/share/src/extension-geodetic-registry/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:640:26)
    at ClientRequest.emit (node:events:532:35)
    at ClientRequest.origin.emit (/Users/username/share/src/extension-geodetic-registry/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:618:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)

```

</details>

**Comment by ribose-jeffreylau** [comment]
Not reproducible now.  Closing.
